### ISSUE TITLE
Update Site Colors

### ISSUE THREAD

**Issue by ruler501** [CubeArtisan/cubeartisan#9]
To better differentiate ourselves from CubeCobra we should use different colors and styles for the site. Something along the lines of `hsl(275, 65, 50)` is a good start for an accent color.

**Comment by thecubemiser** [comment]
I'd suggest using a palette generator like [https://coolors.co/](https://coolors.co/) to lock in colors you want and repeatedly cycle through the rest until you get something you like.

**Comment by ruler501** [comment]
I was thinking I might try to base the Dark theme around my base16 theme ruler501/darkviolet.

**Comment by ruler501** [comment]
First shot at updating the light mode colors is in be53e985c8c746a127a47ddeb9d07fcdaa526e00

**Comment by thecubemiser** [comment]
- Looks like light mode is working
- Lands and Colorless in table view are maybe a little close together in hue/value. Might also want to swap them, since colorless/artifacts are 'canonically' gray/clear now (sadface)
- Dark mode still old colors but can confirm functionality to switch between modes works
